version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: ../backend/Dockerfile
    stdin_open: true
    volumes:
      - lunchero-be:/backend
    ports:
      - "8000:8000"


volumes:
  lunchero-be:
