version: '3'

services:
  sqlite:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    volumes:
      - lunchero-db:/root/db/
    ports:
      - '9000:9000'
    restart: unless-stopped

volumes:
  lunchero-db: